import logging
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional

from core.github_client import GithubClient
from core.llm_client import DeepSeekClient

logger = logging.getLogger("LlamaPReview")

class ContextStrategy(ABC):
    """
    Abstract base class for all context retrieval strategies.
    
    This class implements the Strategy Pattern, allowing the LlamaPReview engine
    to switch between different context gathering algorithms (Search-based, Agent-based, etc.)
    at runtime while sharing core infrastructure like GitHub and LLM clients.
    """

    def __init__(self, github_client: GithubClient, llm_client: DeepSeekClient):
        """
        Initialize the strategy with shared clients.
        
        Args:
            github_client: Wrapper for GitHub API interactions.
            llm_client: Wrapper for DeepSeek API interactions.
        """
        self.github_client = github_client
        self.llm_client = llm_client

    @abstractmethod
    def execute(self, pr_details: str, pr_content: Dict[str, Any], repo_full_name: str) -> str:
        """
        Execute the strategy to retrieve context.
        
        Args:
            pr_details: Markdown description of the PR (generated by core.pr_processor).
            pr_content: Raw JSON object of the PR data.
            repo_full_name: Repository identifier (e.g., "owner/repo").
            
        Returns:
            A string containing the assembled context (code snippets, summaries, etc.)
            ready to be fed into the final Code Review LLM.
        """
        pass

    def _get_latest_sha(self, pr_content: Dict[str, Any]) -> str:
        """
        Helper to extract the latest commit SHA from PR content.
        Reflects original logic: pr_content['commits'][-1]['sha']
        """
        commits = pr_content.get('commits', [])
        if commits and isinstance(commits, list) and len(commits) > 0:
            return commits[-1].get('sha', '')
        return ''

    def _detect_primary_language(self, repo_full_name: str) -> str:
        """
        Helper to detect the repository's primary language.
        
        This attempts to access the underlying llama_github repository object
        via the GithubClient to get the language attribute, mimicking the original
        logic: getattr(repo._repo, "language", None).
        """
        try:
            # Access the internal llama_github repository object
            # Note: This relies on GithubClient exposing _get_llama_repo or similar access
            # Since _get_llama_repo is protected, we use it carefully here as a trusted internal component.
            repo = self.github_client._get_llama_repo(repo_full_name)
            
            # Access the raw PyGithub object inside llama_github's Repository wrapper
            # The structure in llama_github is usually repo._repo for the PyGithub object
            if hasattr(repo, '_repo') and hasattr(repo._repo, 'language'):
                lang = repo._repo.language
                return lang if lang else "Unknown"
            
            return "Unknown"
        except Exception as e:
            logger.warning(f"Failed to detect primary language for {repo_full_name}: {e}")
            return "Unknown"

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the human-readable name of the strategy."""
        pass